### ISSUE TITLE
Support author object

### ISSUE THREAD

**Issue by Legion2** [lorepirri/cayman-blog#9]
When using the `jekyll-seo-tag` plugin you can specify an author object in the `_config.yml`:
```yml
author:
  name: Leon Kiefer
  twitter: Legion2Leon
```

This theme does not render the author information correctly. As it expect the `author` property to be a string. The theme should check if author is an object and use the `name` property, else fallback to the current behavior.

The current version of the theme renders the author as json object:
`{"name"=>"Leon Kiefer", "twitter"=>"Legion2Leon"}`
